language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
script:
  - yarn lint
  - yarn build
branches:
  only:
    - v2-src
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: public
  target-branch: master
  on:
    branch: v2-src