language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email:
    recipients:
      - chen@huchen.me
    on_success: always
    on_failure: always
node_js:
  - '8'
git:
  depth: 3
script:
  - yarn lint
  - yarn build
branches:
  only:
    - develop
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: master
  fqdn: huchen.me
  on:
    branch: develop